JobPortal2/Controllers/JobController.cs
using JobPortal2.Repository;
using JobPortal2.Data;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using JobPortal.Repository;
using JobPortal2.Models;
using System.Security.Claims;
using JobPortal2.Models.DBObjects;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using Microsoft.AspNetCore.Authorization;
using System.Data;

namespace JobPortal2.Controllers
{
    public class JobController : Controller

    {
        private ApplicationDbContext _DbContext;

        private JobRepository jobRepository;

        private RecruiterRepository _recruiterRepository;

        private CandidateRepository _candidateRepository;

        private ApplicationRepository _applicationRepository;
        public JobController(ApplicationDbContext dbContext)
        {
            jobRepository = new JobRepository(dbContext);
            _recruiterRepository = new RecruiterRepository(dbContext);
            _DbContext= dbContext;
            _candidateRepository = new CandidateRepository(dbContext);
            _applicationRepository = new ApplicationRepository(dbContext);
        }
      
        // GET: JobController
        public ActionResult Index()
        {
            var list = jobRepository.GetAllJobs();
            return View(list);
        }

        // GET: JobController/Details/5
        public ActionResult Details(Guid id)
        {
            var model = jobRepository.GetJobId(id);
            return View("JobDetails", model);
        }

        // GET: JobController/Create
        public ActionResult Create()
        {
            return View("CreateJob");
        }

        // POST: JobController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                var model = new JobModel();
                if (User.Identity.IsAuthenticated)
                {
                    var email = User.Identity.Name;
                    var user = _recruiterRepository.GetRecruiterEmail(email);
                    model.IdRecruiter = user.IdRecruiter;

                }
                

                var task = TryUpdateModelAsync(model);
                task.Wait();
                if (task.Result)
                {
                    jobRepository.InsertJob(model);
                }
                return RedirectToAction("Index");
            }
            catch
            {
                return View("CreateJob");
            }
        }

        // GET: JobController/Edit/5
        [Authorize(Roles = "Recruiter")]
        public ActionResult Edit(Guid id)
        {
            var model = jobRepository.GetJobId(id);
            return View("EditJob", model);
        }

        // POST: JobController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Guid id, IFormCollection collection)
        {
            try
            {
                var user = _recruiterRepository.GetRecruiterEmail(User.Identity.Name);
                var model = new JobModel();
                var task = TryUpdateModelAsync(model);
                model.IdJob = id;
                model.IdRecruiter= user.IdRecruiter;
                task.Wait();
                if (task.Result)
                {
                    jobRepository.UpdateJob(model);
                    return RedirectToAction("Index");
                }
                else
                {
                    return RedirectToAction("Index", id);
                }
            }
            catch
            {
                return RedirectToAction("Index", id);
            }
        }

        // GET: JobController/Delete/5
        [Authorize(Roles = "Recruiter")]
        public ActionResult Delete(Guid id)
        {
            var model = jobRepository.GetJobId(id);
            return View("DeleteJob", model);
        }

        // POST: JobController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Guid id, IFormCollection collection)
        {
            try
            {
                jobRepository.DeleteJob(id);
                return RedirectToAction("Index");
            }
            catch
            {
                return View("DeleteJob", id);
            }
        }
        [Authorize(Roles = "Candidate")]
        public ActionResult Save(Guid id)
        {
            if(User.Identity.IsAuthenticated)
            {
                var list = _DbContext.Saveds.ToList();
                var saved = new Saved();
                var email = User.Identity.Name;
                var candidate = _candidateRepository.GetCandidatebyEmail(email); 
                bool alreadySaved = false;
                foreach(var item in list)
                {
                    if(item.IdJob==id && item.IdCandidate== candidate.IdCandidate)
                    {
                        alreadySaved = true;
                    }
                }
                if(alreadySaved == false)
                {
                    
                    saved.IdJob = id;
                    saved.IdCandidate = candidate.IdCandidate;
                    saved.IdSaved = Guid.NewGuid();
                    _DbContext.Saveds.Add(saved);
                    _DbContext.SaveChanges();
                }
            }
            return RedirectToAction("Index");
        }
        [Authorize(Roles = "Candidate")]
        public ActionResult SavedIndex()
        {
            try
            {
                var listofJobs = new List<JobModel>();  
                if(User.Identity.IsAuthenticated)
                {
                    var email = User.Identity.Name;
                    var candidate = _candidateRepository.GetCandidatebyEmail(email);
                    var list = _DbContext.Saveds.ToList();
                    foreach(var item in list)
                    {
                        if(item.IdCandidate == candidate.IdCandidate)
                        {
                            var list2 = new List<Saved>();
                            list2.Add(item);
                            foreach(var item2 in list2)
                            {
                                listofJobs.Add(jobRepository.GetJobId(item2.IdJob));
                            }
                        }
                    }
                }
                return View(listofJobs);
            }
            catch
            {
                return View("Index");
            }
            
        }
        public ActionResult Unsave(Guid id)
        {
            if(User.Identity.IsAuthenticated)
            {
                var saved = _DbContext.Saveds.ToList();
                var candidate = _candidateRepository.GetCandidatebyEmail(User.Identity.Name);
                foreach(Saved item in saved)
                {
                    if(candidate.IdCandidate == item.IdCandidate && id == item.IdJob)
                    {
                        _DbContext.Saveds.Remove(item);
                        _DbContext.SaveChanges();
                    }
                }
            }
            return RedirectToAction("SavedIndex");
        }
        public ActionResult Apply(Guid Id)
        {
            if(User.Identity.IsAuthenticated)
            {
                var application = new ApplicationModel();
                var candidate= _candidateRepository.GetCandidatebyEmail(User.Identity.Name);
                application.IdJob = Id;
                application.IdCandidate = candidate.IdCandidate;
                application.DateTimeAdded = DateTime.Now;
                _applicationRepository.InsertApplication(application);
            }
            return RedirectToAction("Index");
        }
        [Authorize(Roles = "Recruiter")]
        public ActionResult ApplicationIndex(Guid id)
        {
            var indexList = new List<ApplicationModel>();
            if (User.Identity.IsAuthenticated)
            {
                var job = jobRepository.GetJobId(id);
                var recruiter = _recruiterRepository.GetRecruiterEmail(User.Identity.Name);
                var list= _applicationRepository.GetAllApplications();
                
                foreach(var application in list)
                {
                    if(application.IdJob==id && recruiter.IdRecruiter == job.IdRecruiter)
                    {
                         indexList.Add(application);
                    }

                }

                
            }
            return View(indexList);
        }
    }
}

JobPortal2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - JobPortal2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/JobPortal2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">JobPortal</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Job" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Job" asp-action="SavedIndex">Saved</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Recruiter" asp-action="Index">Recruiters</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Candidate" asp-action="Index">Candidates</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Job" asp-action="ApplicationIndex">Applications</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - JobPortal2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>